name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Clona el repositorio en la máquina virtual de GitHub
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configura el entorno de Java 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # 3. Construye el JAR pero salta las pruebas (aún no hay servidor)
    - name: Install Dependencies and Build JAR
      run: mvn clean package -DskipTests

    # 4. Inicia la aplicación en segundo plano
    - name: Start Application in Background
      run: |
        java -jar target/healthtrack-app-1.0-SNAPSHOT-jar-with-dependencies.jar &
        sleep 15 # Dar tiempo extra al servidor para que inicie en el entorno de GitHub

    # 5. Ejecuta las pruebas (ahora sí, con el servidor corriendo)
    - name: Run Tests
      run: mvn test

